// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/Alfagov/goDashboard/models"

func PageContainer(page templ.Component, descriptor []models.PagesDescriptor) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<body class=\"bg-gray-100 h-screen font-sans\"><div class=\"container mx-auto p-4 h-full\">")
		if err != nil {
			return err
		}
		err = NavbarWidget().Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<main class=\"grid h-full grid-cols-4 grid-rows-6 gap-6\">")
		if err != nil {
			return err
		}
		err = Aside(descriptor).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<section class=\"col-span-3 rounded p-4\"><div id=\"page-content\" class=\"grid grid-cols-3 gap-4\">")
		if err != nil {
			return err
		}
		err = page.Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></section></main></div><div id=\"test-id\" class=\"fixed top-4 right-4 text-white px-4 py-2 rounded-md z-50\"></div></body>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
